package main

// siaCodes maps two-letter SIA DC-03 event codes to their descriptions.
var siaCodes = map[string]string{
	"AA": "Alarm - Panel Substitution",
	"AB": "Abort",
	"AN": "Analog Restoral",
	"AR": "AC Restoral",
	"AS": "Analog Service",
	"AT": "AC Trouble",

	"BA": "Burglary Alarm",
	"BB": "Burglary Bypass",
	"BC": "Burglary Cancel",
	"BD": "Swinger Trouble",
	"BE": "Swinger Trouble Restore",
	"BG": "Unverified Event - Burglary",
	"BH": "Burglary Alarm Restore",
	"BJ": "Burglary Trouble Restore",
	"BM": "Burglary Alarm - Cross Point",
	"BR": "Burglary Restoral",
	"BS": "Burglary Supervisory",
	"BT": "Burglary Trouble",
	"BU": "Burglary Unbypass",
	"BV": "Burglary Verified",
	"BX": "Burglary Test",
	"BZ": "Missing Supervision",

	"CA": "Automatic Closing",
	"CD": "Closing Delinquent",
	"CE": "Closing Extend",
	"CF": "Forced Closing",
	"CG": "Close Area",
	"CI": "Fail to Close",
	"CJ": "Late Close",
	"CK": "Early Close",
	"CL": "Closing Report",
	"CM": "Missing Alarm - Recent Closing",
	"CP": "Automatic Arming",
	"CQ": "Remote Arming",
	"CR": "Recent Closing",
	"CS": "Closing Keyswitch",
	"CT": "Late to Open",
	"CW": "Was Force Armed",
	"CZ": "Point Closing",

	"DA": "Card Assigned",
	"DB": "Card Deleted",
	"DC": "Access Closed",
	"DD": "Access Denied",
	"DE": "Request to Enter",
	"DF": "Door Forced",
	"DG": "Access Granted",
	"DH": "Door Left Open - Restoral",
	"DI": "Access Denied - Passback",
	"DJ": "Door Forced - Trouble",
	"DK": "Access Lockout",
	"DL": "Door Left Open - Alarm",
	"DM": "Door Left Open - Trouble",
	"DN": "Door Left Open",
	"DO": "Access Open",
	"DP": "Access Denied - Unauthorized Time",
	"DQ": "Access Denied - Unauthorized Arming State",
	"DR": "Door Restoral",
	"DS": "Door Station",
	"DT": "Access Trouble",
	"DU": "Dealer ID",
	"DV": "Access Denied - Unauthorized Entry Level",
	"DW": "Access Denied - Interlock",
	"DX": "Request to Exit",
	"DY": "Door Locked",
	"DZ": "Access Denied - Door Secured",

	"EA": "Exit Alarm",
	"EE": "Exit Error",
	"EJ": "Expansion Tamper Restore",
	"EM": "Expansion Device Missing",
	"EN": "Expansion Missing Restore",
	"ER": "Expansion Restoral",
	"ES": "Expansion Device Tamper",
	"ET": "Expansion Trouble",
	"EX": "External Device Condition",
	"EZ": "Missing Alarm - Exit Error",

	"FA": "Fire Alarm",
	"FB": "Fire Bypass",
	"FC": "Fire Cancel",
	"FG": "Unverified Event - Fire",
	"FH": "Fire Alarm Restore",
	"FI": "Fire Test Begin",
	"FJ": "Fire Trouble Restore",
	"FK": "Fire Test End",
	"FL": "Fire Alarm Silenced",
	"FM": "Fire Alarm - Cross Point",
	"FQ": "Fire Supervisory Trouble Restore",
	"FR": "Fire Restoral",
	"FS": "Fire Supervisory",
	"FT": "Fire Trouble",
	"FU": "Fire Unbypass",
	"FV": "Fire Supervision Restore",
	"FX": "Fire Test",
	"FY": "Missing Fire Trouble",
	"FZ": "Missing Fire Supervision",

	"GA": "Gas Alarm",
	"GB": "Gas Bypass",
	"GH": "Gas Alarm Restore",
	"GJ": "Gas Trouble Restore",
	"GR": "Gas Restoral",
	"GS": "Gas Supervisory",
	"GT": "Gas Trouble",
	"GU": "Gas Unbypass",
	"GX": "Gas Test",

	"HA": "Holdup Alarm",
	"HB": "Holdup Bypass",
	"HG": "Unverified Event - Holdup",
	"HH": "Holdup Alarm Restore",
	"HJ": "Holdup Trouble Restore",
	"HR": "Holdup Restoral",
	"HS": "Holdup Supervisory",
	"HT": "Holdup Trouble",
	"HU": "Holdup Unbypass",

	"IA": "Equipment Failure Condition",
	"IR": "Equipment Fail - Restoral",

	"JA": "User Code Tamper",
	"JD": "Date Changed",
	"JH": "Holiday Changed",
	"JK": "Latchkey Alert",
	"JL": "Log Threshold",
	"JO": "Log Overflow",
	"JP": "User On Premises",
	"JR": "Schedule Executed",
	"JS": "Schedule Changed",
	"JT": "Time Changed",
	"JV": "User Code Changed",
	"JX": "User Code Deleted",
	"JY": "User Code Added",
	"JZ": "User Level Set",

	"KA": "Heat Alarm",
	"KB": "Heat Bypass",
	"KH": "Heat Alarm Restore",
	"KJ": "Heat Trouble Restore",
	"KR": "Heat Restoral",
	"KS": "Heat Supervisory",
	"KT": "Heat Trouble",
	"KU": "Heat Unbypass",

	"LB": "Local Program",
	"LD": "Local Program Denied",
	"LE": "Listen-in Ended",
	"LF": "Listen-in Begin",
	"LR": "Phone Line Restoral",
	"LS": "Local Program Success",
	"LT": "Phone Line Trouble",
	"LU": "Local Program Fail",
	"LX": "Local Programming Ended",

	"MA": "Medical Alarm",
	"MB": "Medical Bypass",
	"MG": "Unverified Event - Medical",
	"MH": "Medical Alarm Restore",
	"MJ": "Medical Trouble Restore",
	"MR": "Medical Restoral",
	"MS": "Medical Supervisory",
	"MT": "Medical Trouble",
	"MU": "Medical Unbypass",

	"NA": "No Activity",
	"NC": "Network Condition",
	"NF": "Forced Perimeter Arm",
	"NL": "Perimeter Armed",
	"NR": "Network Restoral",
	"NS": "Activity Resumed",
	"NT": "Network Failure",

	"OA": "Automatic Opening",
	"OC": "Cancel Report",
	"OG": "Open Area",
	"OH": "Early to Open from Alarm",
	"OI": "Fail to Open",
	"OJ": "Late Open",
	"OK": "Early Open",
	"OL": "Late to Open from Alarm",
	"OP": "Opening Report",
	"OQ": "Remote Disarming",
	"OR": "Disarm from Alarm",
	"OS": "Opening Keyswitch",
	"OT": "Late to Close",
	"OU": "Output State - Trouble",
	"OV": "Output State - Restore",
	"OZ": "Point Opening",

	"PA": "Panic Alarm",
	"PB": "Panic Bypass",
	"PG": "Unverified Event - Panic",
	"PH": "Panic Alarm Restore",
	"PJ": "Panic Trouble Restore",
	"PR": "Panic Restoral",
	"PS": "Panic Supervisory",
	"PT": "Panic Trouble",
	"PU": "Panic Unbypass",

	"QA": "Emergency Alarm",
	"QB": "Emergency Bypass",
	"QG": "Unverified Event - Emergency",
	"QH": "Emergency Alarm Restore",
	"QJ": "Emergency Trouble Restore",
	"QR": "Emergency Restoral",
	"QS": "Emergency Supervisory",
	"QT": "Emergency Trouble",
	"QU": "Emergency Unbypass",

	"RA": "Remote Programmer Call Failed",
	"RB": "Remote Program Begin",
	"RC": "Relay Close",
	"RD": "Remote Program Denied",
	"RN": "Remote Reset",
	"RO": "Relay Open",
	"RP": "Automatic Test",
	"RR": "Power Up",
	"RS": "Remote Program Success",
	"RT": "Data Lost",
	"RU": "Remote Program Fail",
	"RX": "Manual Test",
	"RY": "Test Off Normal",

	"SA": "Sprinkler Alarm",
	"SB": "Sprinkler Bypass",
	"SC": "Change of State",
	"SH": "Sprinkler Alarm Restore",
	"SJ": "Sprinkler Trouble Restore",
	"SR": "Sprinkler Restoral",
	"SS": "Sprinkler Supervisory",
	"ST": "Sprinkler Trouble",
	"SU": "Sprinkler Unbypass",

	"TA": "Tamper Alarm",
	"TB": "Tamper Bypass",
	"TC": "All Points Tested",
	"TE": "Test End",
	"TH": "Tamper Alarm Restore",
	"TJ": "Tamper Trouble Restore",
	"TP": "Walk Test Point",
	"TR": "Tamper Restoral",
	"TS": "Test Start",
	"TT": "Tamper Trouble",
	"TU": "Tamper Unbypass",
	"TW": "Area Watch Start",
	"TX": "Test Report",
	"TZ": "Area Watch End",

	"UA": "Untyped Zone Alarm",
	"UB": "Untyped Zone Bypass",
	"UG": "Unverified Event - Untyped",
	"UH": "Untyped Alarm Restore",
	"UJ": "Untyped Trouble Restore",
	"UR": "Untyped Zone Restoral",
	"US": "Untyped Zone Supervisory",
	"UT": "Untyped Zone Trouble",
	"UU": "Untyped Zone Unbypass",
	"UX": "Undefined",
	"UY": "Untyped Missing Trouble",
	"UZ": "Untyped Missing Alarm",

	"VI": "Printer Paper In",
	"VO": "Printer Paper Out",
	"VR": "Printer Restore",
	"VT": "Printer Trouble",
	"VX": "Printer Test",
	"VY": "Printer Online",
	"VZ": "Printer Offline",

	"WA": "Water Alarm",
	"WB": "Water Bypass",
	"WH": "Water Alarm Restore",
	"WJ": "Water Trouble Restore",
	"WR": "Water Restoral",
	"WS": "Water Supervisory",
	"WT": "Water Trouble",
	"WU": "Water Unbypass",

	"XA": "Extra Account Report",
	"XE": "Extra Point",
	"XF": "Extra RF Point",
	"XH": "RF Interference Restoral",
	"XI": "Sensor Reset",
	"XJ": "RF Receiver Tamper Restoral",
	"XL": "Low Received Signal",
	"XM": "Missing Alarm - Cross Point",
	"XQ": "RF Interference",
	"XR": "Transmitter Battery Restoral",
	"XS": "RF Receiver Tamper",
	"XT": "Transmitter Battery Trouble",
	"XW": "Forced Point",
	"XX": "Fail to Test",

	"YA": "Bell Fault",
	"YB": "Busy Seconds",
	"YC": "Communications Fail",
	"YD": "Receiver Line Card Trouble",
	"YE": "Receiver Line Card Restored",
	"YF": "Parameter Checksum Fail",
	"YG": "Parameter Changed",
	"YH": "Bell Restored",
	"YI": "Overcurrent Trouble",
	"YJ": "Overcurrent Restore",
	"YK": "Communications Restoral",
	"YM": "System Battery Missing",
	"YN": "Invalid Report",
	"YO": "Unknown Message",
	"YP": "Power Supply Trouble",
	"YQ": "Power Supply Restored",
	"YR": "System Battery Restoral",
	"YS": "Communications Trouble",
	"YT": "System Battery Trouble",
	"YU": "Diagnostic Error",
	"YW": "Watchdog Reset",
	"YX": "Service Required",
	"YY": "Status Report",
	"YZ": "Service Completed",

	"ZA": "Freeze Alarm",
	"ZB": "Freeze Bypass",
	"ZH": "Freeze Alarm Restore",
	"ZJ": "Freeze Trouble Restore",
	"ZR": "Freeze Restoral",
	"ZS": "Freeze Supervisory",
	"ZT": "Freeze Trouble",
	"ZU": "Freeze Unbypass",
}

// DescribeSIA returns the description of a two-letter SIA event code,
// or "" if the code is unknown.
func DescribeSIA(code string) string {
	return siaCodes[code]
}
